version: '3'

services: 
  admin: 
    container_name: cxp_admin
    build: .
    environment:
      - NODE_ENV=development
      - REACT_APP_NAME=admin
      - REACT_APP_EMULATOR_ADMIN_HOST=http://localhost:9099
      - REACT_APP_EMULATOR_WEB_HOST=http://localhost:9098
      - REACT_APP_API_URL=http://localhost:5000/api/v1/
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      -  .:/srv/app
      - /srv/app/node_modules
    ports:
      - 3001:3000

networks:
  default:
    external: true
    name: server_default
