name: Sync Mirror Repo 

on:
  release:
    types: [published, edited]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:conexperto/admin.git"
          source_branch: "main"
          destination_repo: "git@github.com:conexpertoteam/admin.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

