name: Sync Mirror Repo Staging

on:
  push: 
    branches: 'feature/*'
  pull_request:
    branches: 'feature/*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:conexperto/admin.git"
          source_branch: "staging"
          destination_repo: "git@github.com:conexpertoteam/admin.git"
          destination_branch: "staging"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
